# Generated by Django 3.2.16 on 2025-05-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20250504_1933'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['user', 'following'], name='posts_follo_user_id_4b6ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['pub_date', 'id'], name='posts_post_pub_dat_cce227_idx'),
        ),
    ]
