# Generated by Django 3.2.16 on 2025-05-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20250506_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['user__username', 'following__username', 'id'], 'verbose_name': 'подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
