# Generated by Django 5.2.1 on 2025-05-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_comment_options_alter_comment_author_and_more'),
        ('posts', '0004_auto_20220720_1125'),
        ('posts', '0004_remove_follow_unique_user_following_and_more'),
        ('posts', '0005_follow_prevent_self_follow'),
    ]

    operations = [
    ]
